### ISSUE TITLE
Code-Beispiele, Präsentationsfolien und Bericht zippen und hochladen

### ISSUE THREAD

**Issue by wuethrich44** [alexsuter/golang-experience#5]
Alles zusammen-gezippt in 1 Datei mit Namensschema [Sprache]-[Stud1]-[Stud2].zip (also z.B. „Java-Diehl-Arnold.zip“) und hochgeladen in‘s Ilias.

![image](https://cloud.githubusercontent.com/assets/6050639/11663829/b6164a44-9dde-11e5-96f4-d9abe0759b0f.png)

![image](https://cloud.githubusercontent.com/assets/6050639/11663834/c05353da-9dde-11e5-8a1f-85ce04a631d9.png)

![image](https://cloud.githubusercontent.com/assets/6050639/11663842/ca2dbd50-9dde-11e5-8c65-a8b2a42da4e6.png)

**Comment by alexsuter** [comment]
Ich mache noch kurz das Readme.txt

**Comment by wuethrich44** [comment]
:+1: Ich schmeiss es dann am Abend auf ILIAS

**Comment by alexsuter** [comment]
Danke. Mit dem Bericht bin ich dann in 30 Minuten fertig.

**Comment by alexsuter** [comment]
@wuethrich44  don't forget

**Comment by wuethrich44** [comment]
Ich lade es jetzt gleich hoch

**Comment by wuethrich44** [comment]
Done
